In [1]:
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from nltk.stem import WordNetLemmatizer

# Pastikan resource NLTK tersedia
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

# Load data (pakai engine="python" biar fleksibel)
df = pd.read_csv("ALL_DATA_BERITA_22-24.csv", sep=",")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\WIN10\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\WIN10\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\WIN10\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [2]:
df

,tanggal,kategori,judul,url,konten
0,2022-01-01,ekonomi,SKK Migas Targetkan Pengeboran 700 Sumur di Ta...,https://finance.detik.com/energi/d-5880032/skk...,Dalam rangka mengoptimalkan lifting migas di t...
1,2022-01-01,ekonomi,"Ekspor Batu Bara Dilarang Sementara, Pengusaha...",https://finance.detik.com/energi/d-5880129/eks...,Pemerintah menyetop sementara ekspor batu bara...
2,2022-01-01,ekonomi,Jaksa Agung Puji Erick Thohir Bantu Bongkar Ko...,https://finance.detik.com/moneter/d-5880248/ja...,Jaksa Agung Burhanuddin memberikan pujian kepa...
3,2022-01-01,ekonomi,"Terbang dengan Ancaman Omicron, Pilot Maskapai...",https://finance.detik.com/berita-ekonomi-bisni...,Maskapai penerbangan Amerika Serikat (AS) Unit...
4,2022-01-01,ekonomi,"450 Karyawannya Mogok Kerja, Warren Buffett Ma...",https://finance.detik.com/berita-ekonomi-bisni...,Ratusan karyawan dari salah satu anak perusaha...
...,...,...,...,...,...
17649,2024-12-31,ekonomi,Menteri Keuangan Sri Mulyani Indrawati menjela...,https://finance.detik.com/berita-ekonomi-bisni...,Menteri Keuangan Sri Mulyani Indrawati menjela...
17650,2024-12-31,ekonomi,"""Seperti yang sudah saya sampaikan sebelumnya,...",https://finance.detik.com/berita-ekonomi-bisni...,"""Seperti yang sudah saya sampaikan sebelumnya,..."
17651,2024-12-31,ekonomi,Kemendag mempunyai sembilan gudang SRG dan sat...,https://finance.detik.com/berita-ekonomi-bisni...,Kemendag mempunyai sembilan gudang SRG dan sat...
17652,2024-12-31,ekonomi,"Waspada Penipuan Mengatasnamakan Bea Cukai, In...",https://finance.detik.com/berita-ekonomi-bisni...,"Bulan Mei lalu, Zahra menemukan toko online di..."
17653,2024-12-31,ekonomi,Sejarah USD (Dolar AS) Jadi Patokan Mata Uang ...,https://finance.detik.com/berita-ekonomi-bisni...,"Padahal pada zaman dahulu, emas selalu menjadi..."

In [3]:
df.isna().sum()

tanggal       0
kategori      0
judul        48
url           0
konten      282
dtype: int64

In [4]:
df=df.dropna(subset=['konten'])

In [5]:
df.isna().sum()

tanggal      0
kategori     0
judul       31
url          0
konten       0
dtype: int64

In [6]:
import pandas as pd

# contoh: baca data
# df = pd.read_excel("data.xlsx")

df['judul'] = df['judul'].replace("", pd.NA)

def make_title(text, max_words=10):
    if pd.isna(text) or not isinstance(text, str):
        return text
    # ambil kalimat pertama, lalu batasi max_words kata
    first_sentence = text.split('.')[0]
    words = first_sentence.split()
    return " ".join(words[:max_words])

df['judul'] = df['judul'].fillna(df['konten'].apply(lambda x: make_title(x, 10)))

C:\Users\WIN10\AppData\Local\Temp\ipykernel_14964\631720607.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['judul'] = df['judul'].replace("", pd.NA)
C:\Users\WIN10\AppData\Local\Temp\ipykernel_14964\631720607.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['judul'] = df['judul'].fillna(df['konten'].apply(lambda x: make_title(x, 10)))

In [7]:
df.isna().sum()

tanggal     0
kategori    0
judul       0
url         0
konten      0
dtype: int64

In [8]:
# hitung total baris duplikat (selain yang pertama)
jumlah_duplikat = df['konten'].duplicated().sum()
print("Jumlah duplikat konten:", jumlah_duplikat)

# atau kalau mau tahu berapa nilai unik yg duplikat
jumlah_nilai_duplikat = (df['konten'].value_counts() > 1).sum()
print("Jumlah nilai konten yg punya duplikat:", jumlah_nilai_duplikat)

Jumlah duplikat konten: 261
Jumlah nilai konten yg punya duplikat: 255

In [9]:
df=df[df.duplicated(subset=['konten'], keep=False) == False]

In [10]:
# hitung total baris duplikat (selain yang pertama)
jumlah_duplikat = df['konten'].duplicated().sum()
print("Jumlah duplikat konten:", jumlah_duplikat)

# atau kalau mau tahu berapa nilai unik yg duplikat
jumlah_nilai_duplikat = (df['konten'].value_counts() > 1).sum()
print("Jumlah nilai konten yg punya duplikat:", jumlah_nilai_duplikat)

Jumlah duplikat konten: 0
Jumlah nilai konten yg punya duplikat: 0

In [11]:
df.isna().sum()

tanggal     0
kategori    0
judul       0
url         0
konten      0
dtype: int64

In [12]:
# ==== 1. Case Folding ====
def case_folding(text):
    return text.lower()

# ==== 2. Tokenisasi ====
def tokenize(text):
    return word_tokenize(text)

# ==== 3. Stopword Removal ====
stop_words = set(stopwords.words('indonesian'))
def remove_stopwords(tokens):
    return [word for word in tokens if word not in stop_words]

# ==== 4. Lemmatization ====
lemmatizer = WordNetLemmatizer()
def lemmatize(tokens):
    return [lemmatizer.lemmatize(word) for word in tokens]

# ==== 5. Stemming (Sastrawi) ====
factory = StemmerFactory()
stemmer = factory.create_stemmer()
def stemming(tokens):
    return [stemmer.stem(word) for word in tokens]

In [13]:
# ==== Pipeline Text Cleaning ====
def clean_text(text):
    if pd.isna(text):
        return ""
    text = case_folding(text)
    tokens = tokenize(text)
    tokens = remove_stopwords(tokens)
    tokens = lemmatize(tokens)
    tokens = stemming(tokens)
    return " ".join(tokens)

In [14]:
# Terapkan ke kolom 'konten'
if 'konten' in df.columns:
    df['konten_clean'] = df['konten'].apply(clean_text)
else:
    print("⚠️ Tidak ditemukan kolom bernama 'konten'. Cek nama kolom di file CSV.")

KeyboardInterrupt:

In [ ]:
df.to_csv("DATA_CLEANING_FIX_BANGET.csv", index=False, encoding="utf-8")

In [70]:
df = pd.read_csv("DATA_CLEANING_FIX_BANGET.csv")
df

,tanggal,kategori,judul,url,konten,konten_clean
0,2022-01-05,ekonomi,"Soroti Minyak Goreng Mahal, Ma'ruf Amin: Janga...",https://finance.detik.com/berita-ekonomi-bisni...,Harga minyak goreng masih menjadi sorotan publ...,harga minyak goreng sorot publik lantar harga...
1,2022-01-05,ekonomi,"Lagi Terbelit Utang, Evergrande Disuruh Hancur...",https://finance.detik.com/properti/d-5885844/l...,"Belum selesai masalah utang, pengembang proper...",selesai utang kembang properti china evergran...
2,2022-01-05,ekonomi,Desain Istana Presiden Ibu Kota Baru Diklaim S...,https://finance.detik.com/properti/d-5885825/d...,Desain kawasan Istana Kepresidenan di ibu kota...,desain kawasan istana presiden kota negara ik...
3,2022-01-05,ekonomi,Sri Mulyani Kasih Tugas Khusus ke Bos Baru LPE...,https://finance.detik.com/moneter/d-5885624/sr...,Lembaga Pembiayaan Ekspor Indonesia (LPEI) mem...,lembaga biaya ekspor indonesia lpei milik ke...
4,2022-01-05,ekonomi,Perbankan Tak Bisa Mendadak Setop Biayai Batu ...,https://finance.detik.com/energi/d-5885790/per...,Meskipun saat ini sektor keuangan perbankan di...,sektor uang perban arah dukung terap ekonomi h...
...,...,...,...,...,...,...
16851,2024-12-31,ekonomi,Menteri Keuangan Sri Mulyani Indrawati menjela...,https://finance.detik.com/berita-ekonomi-bisni...,Menteri Keuangan Sri Mulyani Indrawati menjela...,menteri uang sri mulyani indrawati barang golo...
16852,2024-12-31,ekonomi,"""Seperti yang sudah saya sampaikan sebelumnya,...",https://finance.detik.com/berita-ekonomi-bisni...,"""Seperti yang sudah saya sampaikan sebelumnya,...",koordinasi dpr perintah putus naik tarif pp...
16853,2024-12-31,ekonomi,Kemendag mempunyai sembilan gudang SRG dan sat...,https://finance.detik.com/berita-ekonomi-bisni...,Kemendag mempunyai sembilan gudang SRG dan sat...,kemendag sembilan gudang srg gudang sistem con...
16854,2024-12-31,ekonomi,"Waspada Penipuan Mengatasnamakan Bea Cukai, In...",https://finance.detik.com/berita-ekonomi-bisni...,"Bulan Mei lalu, Zahra menemukan toko online di...",mei zahra temu toko online instagram nama or...
16855,2024-12-31,ekonomi,Sejarah USD (Dolar AS) Jadi Patokan Mata Uang ...,https://finance.detik.com/berita-ekonomi-bisni...,"Padahal pada zaman dahulu, emas selalu menjadi...",zaman emas patok mata uang anggap milik nilai...

In [71]:
print(df.columns)

Index(['tanggal', 'kategori', 'judul', 'url', 'konten', 'konten_clean'], dtype='object')

In [72]:
df = df.drop(columns=['konten'])
df

,tanggal,kategori,judul,url,konten_clean
0,2022-01-05,ekonomi,"Soroti Minyak Goreng Mahal, Ma'ruf Amin: Janga...",https://finance.detik.com/berita-ekonomi-bisni...,harga minyak goreng sorot publik lantar harga...
1,2022-01-05,ekonomi,"Lagi Terbelit Utang, Evergrande Disuruh Hancur...",https://finance.detik.com/properti/d-5885844/l...,selesai utang kembang properti china evergran...
2,2022-01-05,ekonomi,Desain Istana Presiden Ibu Kota Baru Diklaim S...,https://finance.detik.com/properti/d-5885825/d...,desain kawasan istana presiden kota negara ik...
3,2022-01-05,ekonomi,Sri Mulyani Kasih Tugas Khusus ke Bos Baru LPE...,https://finance.detik.com/moneter/d-5885624/sr...,lembaga biaya ekspor indonesia lpei milik ke...
4,2022-01-05,ekonomi,Perbankan Tak Bisa Mendadak Setop Biayai Batu ...,https://finance.detik.com/energi/d-5885790/per...,sektor uang perban arah dukung terap ekonomi h...
...,...,...,...,...,...
16851,2024-12-31,ekonomi,Menteri Keuangan Sri Mulyani Indrawati menjela...,https://finance.detik.com/berita-ekonomi-bisni...,menteri uang sri mulyani indrawati barang golo...
16852,2024-12-31,ekonomi,"""Seperti yang sudah saya sampaikan sebelumnya,...",https://finance.detik.com/berita-ekonomi-bisni...,koordinasi dpr perintah putus naik tarif pp...
16853,2024-12-31,ekonomi,Kemendag mempunyai sembilan gudang SRG dan sat...,https://finance.detik.com/berita-ekonomi-bisni...,kemendag sembilan gudang srg gudang sistem con...
16854,2024-12-31,ekonomi,"Waspada Penipuan Mengatasnamakan Bea Cukai, In...",https://finance.detik.com/berita-ekonomi-bisni...,mei zahra temu toko online instagram nama or...
16855,2024-12-31,ekonomi,Sejarah USD (Dolar AS) Jadi Patokan Mata Uang ...,https://finance.detik.com/berita-ekonomi-bisni...,zaman emas patok mata uang anggap milik nilai...

In [73]:
saham_keywords = [
    "saham", "ihsg", "bursa", "bei", "emiten", "investor", "investasi", "pasar modal",
    "ipo", "dividen", "rupiah", "kurs", "obligasi", "indeks", "ekonomi", "perdagangan",
    "market", "harga", "komoditas", "delisting", "suspensi perdagangan", "listing",
    "volatility", "kapitalisasi", "suku bunga", "inflasi", "perekonomian",
    "defisit", "surplus"
]

In [74]:
import re

pattern = re.compile(r'\b(?:' + '|'.join(saham_keywords) + r')\b', flags=re.IGNORECASE)

In [75]:
mask = df['judul'].str.contains(pattern, na=False) | df['konten_clean'].str.contains(pattern, na=False)
berita_saham = df[mask]

In [76]:
berita_saham

,tanggal,kategori,judul,url,konten_clean
0,2022-01-05,ekonomi,"Soroti Minyak Goreng Mahal, Ma'ruf Amin: Janga...",https://finance.detik.com/berita-ekonomi-bisni...,harga minyak goreng sorot publik lantar harga...
1,2022-01-05,ekonomi,"Lagi Terbelit Utang, Evergrande Disuruh Hancur...",https://finance.detik.com/properti/d-5885844/l...,selesai utang kembang properti china evergran...
3,2022-01-05,ekonomi,Sri Mulyani Kasih Tugas Khusus ke Bos Baru LPE...,https://finance.detik.com/moneter/d-5885624/sr...,lembaga biaya ekspor indonesia lpei milik ke...
4,2022-01-05,ekonomi,Perbankan Tak Bisa Mendadak Setop Biayai Batu ...,https://finance.detik.com/energi/d-5885790/per...,sektor uang perban arah dukung terap ekonomi h...
5,2022-01-05,ekonomi,Harapan Jokowi Resmikan Pasar Johar: Ekonomi R...,https://finance.detik.com/berita-ekonomi-bisni...,presiden joko widodo resmi pasar johar kota se...
...,...,...,...,...,...
16850,2024-12-31,ekonomi,Hal tersebut disampaikan oleh Direktur Jendera...,https://finance.detik.com/energi/d-7712214/kad...,direktur jenderal ketenagalistrikan menteri en...
16851,2024-12-31,ekonomi,Menteri Keuangan Sri Mulyani Indrawati menjela...,https://finance.detik.com/berita-ekonomi-bisni...,menteri uang sri mulyani indrawati barang golo...
16853,2024-12-31,ekonomi,Kemendag mempunyai sembilan gudang SRG dan sat...,https://finance.detik.com/berita-ekonomi-bisni...,kemendag sembilan gudang srg gudang sistem con...
16854,2024-12-31,ekonomi,"Waspada Penipuan Mengatasnamakan Bea Cukai, In...",https://finance.detik.com/berita-ekonomi-bisni...,mei zahra temu toko online instagram nama or...
16855,2024-12-31,ekonomi,Sejarah USD (Dolar AS) Jadi Patokan Mata Uang ...,https://finance.detik.com/berita-ekonomi-bisni...,zaman emas patok mata uang anggap milik nilai...

In [77]:
print("jumlah data awal", len(df))
print("jumlah berita saham", len(berita_saham))

jumlah data awal 16856
jumlah berita saham 10648

In [78]:
berita_saham.isna().sum()

tanggal         0
kategori        0
judul           0
url             0
konten_clean    0
dtype: int64

In [ ]:
berita_saham.to_csv("ALL_SAHAM_RELEVANCY_NEWS.csv")

In [46]:
df = pd.read_csv("ALL_SAHAM_RELEVANCY_NEWS.csv")
df

,Unnamed: 0,tanggal,kategori,judul,url,konten_clean
0,0,2022-01-05,ekonomi,"Soroti Minyak Goreng Mahal, Ma'ruf Amin: Janga...",https://finance.detik.com/berita-ekonomi-bisni...,harga minyak goreng sorot publik lantar harga...
1,1,2022-01-05,ekonomi,"Lagi Terbelit Utang, Evergrande Disuruh Hancur...",https://finance.detik.com/properti/d-5885844/l...,selesai utang kembang properti china evergran...
2,3,2022-01-05,ekonomi,Sri Mulyani Kasih Tugas Khusus ke Bos Baru LPE...,https://finance.detik.com/moneter/d-5885624/sr...,lembaga biaya ekspor indonesia lpei milik ke...
3,4,2022-01-05,ekonomi,Perbankan Tak Bisa Mendadak Setop Biayai Batu ...,https://finance.detik.com/energi/d-5885790/per...,sektor uang perban arah dukung terap ekonomi h...
4,5,2022-01-05,ekonomi,Harapan Jokowi Resmikan Pasar Johar: Ekonomi R...,https://finance.detik.com/berita-ekonomi-bisni...,presiden joko widodo resmi pasar johar kota se...
...,...,...,...,...,...,...
10643,16850,2024-12-31,ekonomi,Hal tersebut disampaikan oleh Direktur Jendera...,https://finance.detik.com/energi/d-7712214/kad...,direktur jenderal ketenagalistrikan menteri en...
10644,16851,2024-12-31,ekonomi,Menteri Keuangan Sri Mulyani Indrawati menjela...,https://finance.detik.com/berita-ekonomi-bisni...,menteri uang sri mulyani indrawati barang golo...
10645,16853,2024-12-31,ekonomi,Kemendag mempunyai sembilan gudang SRG dan sat...,https://finance.detik.com/berita-ekonomi-bisni...,kemendag sembilan gudang srg gudang sistem con...
10646,16854,2024-12-31,ekonomi,"Waspada Penipuan Mengatasnamakan Bea Cukai, In...",https://finance.detik.com/berita-ekonomi-bisni...,mei zahra temu toko online instagram nama or...
10647,16855,2024-12-31,ekonomi,Sejarah USD (Dolar AS) Jadi Patokan Mata Uang ...,https://finance.detik.com/berita-ekonomi-bisni...,zaman emas patok mata uang anggap milik nilai...

In [47]:
df = df.drop(columns=['Unnamed: 0'])
df.head()

,tanggal,kategori,judul,url,konten_clean
0,2022-01-05,ekonomi,"Soroti Minyak Goreng Mahal, Ma'ruf Amin: Janga...",https://finance.detik.com/berita-ekonomi-bisni...,harga minyak goreng sorot publik lantar harga...
1,2022-01-05,ekonomi,"Lagi Terbelit Utang, Evergrande Disuruh Hancur...",https://finance.detik.com/properti/d-5885844/l...,selesai utang kembang properti china evergran...
2,2022-01-05,ekonomi,Sri Mulyani Kasih Tugas Khusus ke Bos Baru LPE...,https://finance.detik.com/moneter/d-5885624/sr...,lembaga biaya ekspor indonesia lpei milik ke...
3,2022-01-05,ekonomi,Perbankan Tak Bisa Mendadak Setop Biayai Batu ...,https://finance.detik.com/energi/d-5885790/per...,sektor uang perban arah dukung terap ekonomi h...
4,2022-01-05,ekonomi,Harapan Jokowi Resmikan Pasar Johar: Ekonomi R...,https://finance.detik.com/berita-ekonomi-bisni...,presiden joko widodo resmi pasar johar kota se...

In [48]:
# Daftar kata kunci
positif_keywords = [
    "menguat", "rebound", "bullish", "surplus", "naik", "melonjak",
    "penguatan", "stabil", "optimis", "pulih", "rekor", "melambung"
]
negatif_keywords = [
    "melemah", "anjlok", "bearish", "defisit", "turun", "merosot",
    "penurunan", "tertekan", "resesi", "krisis", "minus", "collapse", "pelemahan"
]

In [49]:
# Fungsi untuk memberi label sentimen
def get_sentiment(text):
    text = str(text).lower()
    if any(word in text for word in positif_keywords):
        return "positif"
    elif any(word in text for word in negatif_keywords):
        return "negatif"
    else:
        return "netral"

In [50]:
# Terapkan ke kolom judul/konten (misal judul)
df["sentimen_saham"] = df["konten_clean"].apply(get_sentiment)

In [51]:
print(df["sentimen_saham"].value_counts())

sentimen_saham
netral     6416
positif    3056
negatif    1176
Name: count, dtype: int64

In [52]:
df.isna().sum()

tanggal           0
kategori          0
judul             0
url               0
konten_clean      0
sentimen_saham    0
dtype: int64

In [53]:
df.to_csv("ALL_SAHAM_SENTIMEN_KEYWORDS.csv", index=False)

In [54]:
df = pd.read_csv("ALL_SAHAM_SENTIMEN_KEYWORDS.csv")

In [55]:
df

,tanggal,kategori,judul,url,konten_clean,sentimen_saham
0,2022-01-05,ekonomi,"Soroti Minyak Goreng Mahal, Ma'ruf Amin: Janga...",https://finance.detik.com/berita-ekonomi-bisni...,harga minyak goreng sorot publik lantar harga...,positif
1,2022-01-05,ekonomi,"Lagi Terbelit Utang, Evergrande Disuruh Hancur...",https://finance.detik.com/properti/d-5885844/l...,selesai utang kembang properti china evergran...,negatif
2,2022-01-05,ekonomi,Sri Mulyani Kasih Tugas Khusus ke Bos Baru LPE...,https://finance.detik.com/moneter/d-5885624/sr...,lembaga biaya ekspor indonesia lpei milik ke...,netral
3,2022-01-05,ekonomi,Perbankan Tak Bisa Mendadak Setop Biayai Batu ...,https://finance.detik.com/energi/d-5885790/per...,sektor uang perban arah dukung terap ekonomi h...,negatif
4,2022-01-05,ekonomi,Harapan Jokowi Resmikan Pasar Johar: Ekonomi R...,https://finance.detik.com/berita-ekonomi-bisni...,presiden joko widodo resmi pasar johar kota se...,netral
...,...,...,...,...,...,...
10643,2024-12-31,ekonomi,Hal tersebut disampaikan oleh Direktur Jendera...,https://finance.detik.com/energi/d-7712214/kad...,direktur jenderal ketenagalistrikan menteri en...,positif
10644,2024-12-31,ekonomi,Menteri Keuangan Sri Mulyani Indrawati menjela...,https://finance.detik.com/berita-ekonomi-bisni...,menteri uang sri mulyani indrawati barang golo...,positif
10645,2024-12-31,ekonomi,Kemendag mempunyai sembilan gudang SRG dan sat...,https://finance.detik.com/berita-ekonomi-bisni...,kemendag sembilan gudang srg gudang sistem con...,positif
10646,2024-12-31,ekonomi,"Waspada Penipuan Mengatasnamakan Bea Cukai, In...",https://finance.detik.com/berita-ekonomi-bisni...,mei zahra temu toko online instagram nama or...,netral
10647,2024-12-31,ekonomi,Sejarah USD (Dolar AS) Jadi Patokan Mata Uang ...,https://finance.detik.com/berita-ekonomi-bisni...,zaman emas patok mata uang anggap milik nilai...,positif

In [56]:
print(df["sentimen_saham"].value_counts())

sentimen_saham
netral     6416
positif    3056
negatif    1176
Name: count, dtype: int64

In [57]:
df_positif = df[df['sentimen_saham'] == 'positif']
df_negatif = df[df['sentimen_saham'] == 'negatif']
df_netral  = df[df['sentimen_saham'] == 'netral']

In [65]:
from sklearn.utils import resample

target = 3000

netral_down = resample(df_netral,
                       replace=False,
                       n_samples=target,
                       random_state=42)
positif_up = resample(df_positif,
                      replace=True,
                      n_samples=target,
                      random_state=42)
negatif_up = resample(df_negatif,
                      replace=True,
                      n_samples=target,
                      random_state=42)

In [66]:
# Gabungkan hasil balancing
df_balanced = pd.concat([netral_down, positif_up, negatif_up])

# Cek distribusi baru
df_balanced['sentimen_saham'].value_counts()

sentimen_saham
netral     3000
positif    3000
negatif    3000
Name: count, dtype: int64

In [67]:
from sklearn.model_selection import train_test_split

# Fitur dan label
X = df_balanced['konten_clean']   # ganti kalau nama kolom teks beda
y = df_balanced['sentimen_saham']

# 1. Train 80%, sisa 20%
X_train, X_temp, y_train, y_temp = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# 2. Validation 10%, Test 10%
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp,
    test_size=0.5,
    random_state=42,
    stratify=y_temp
)

# Cek ukuran
print("Train:", len(X_train))
print("Validation:", len(X_val))
print("Test:", len(X_test))

# Cek distribusi label
print("\nDistribusi Train:\n", y_train.value_counts())
print("\nDistribusi Validation:\n", y_val.value_counts())
print("\nDistribusi Test:\n", y_test.value_counts())

Train: 7200
Validation: 900
Test: 900

Distribusi Train:
 sentimen_saham
positif    2400
negatif    2400
netral     2400
Name: count, dtype: int64

Distribusi Validation:
 sentimen_saham
netral     300
positif    300
negatif    300
Name: count, dtype: int64

Distribusi Test:
 sentimen_saham
netral     300
positif    300
negatif    300
Name: count, dtype: int64

In [68]:
import pandas as pd

# Train
train_df = pd.DataFrame({
    "text": X_train.values,
    "label": y_train.values
})

# Validation
val_df = pd.DataFrame({
    "text": X_val.values,
    "label": y_val.values
})

# Test
test_df = pd.DataFrame({
    "text": X_test.values,
    "label": y_test.values
})

# Simpan ke CSV
train_df.to_csv("train.csv", index=False)
val_df.to_csv("val.csv", index=False)
test_df.to_csv("test.csv", index=False)

print("File berhasil disimpan:")
print("- train.csv")
print("- val.csv")
print("- test.csv")

File berhasil disimpan:
- train.csv
- val.csv
- test.csv

In [31]:
df_balanced

,tanggal,kategori,judul,url,konten_clean,sentimen_saham
8475,2024-06-08,ekonomi,"Kapan Lagi Beli AC Diskon Rp 1,3 Juta, Cuma di...",https://finance.detik.com/berita-ekonomi-bisni...,transmart full day sale hadir besok minggu 9 ...,netral
8846,2024-07-15,ekonomi,OJK Buka Suara soal Kabar Muhammadiyah Mau Cap...,https://finance.detik.com/moneter/d-7440244/oj...,organisasi muhammadiyah sorot alih dana pt ban...,netral
2031,2022-07-26,ekonomi,"Bertemu Jokowi, Xi Jinping Mau Genjot Impor Pr...",https://finance.detik.com/berita-ekonomi-bisni...,presiden joko widodo jokowi temu bilateral p...,netral
2553,2022-09-14,ekonomi,"Bicara di Forum ASEAN, Bahlil Singgung Gugatan...",https://finance.detik.com/energi/d-6292236/bic...,menteri investasi kepala badan koordinasi tana...,netral
8461,2024-06-07,ekonomi,"Transmart Banjir Diskon Produk Susu, Sampo, Sn...",https://finance.detik.com/berita-ekonomi-bisni...,transmart tawar promo tarik pekan produk cont...,netral
...,...,...,...,...,...,...
1,2022-01-05,ekonomi,"Lagi Terbelit Utang, Evergrande Disuruh Hancur...",https://finance.detik.com/properti/d-5885844/l...,selesai utang kembang properti china evergran...,negatif
2342,2022-08-25,ekonomi,Ditjen Pajak Sosialisasikan UU Cipta Kerja di ...,https://finance.detik.com/berita-ekonomi-bisni...,direktorat jenderal pajak djp perintah provi...,negatif
8636,2024-06-24,ekonomi,Petinggi Bank Dunia Respons Rencana Prabowo Pi...,https://finance.detik.com/berita-ekonomi-bisni...,perintah komando prabowo subianto-gibran rakab...,negatif
2729,2022-10-03,ekonomi,Contoh Jurnal Umum Perusahaan Dagang dan Cara ...,https://finance.detik.com/solusiukm/d-6327272/...,bahas jurnal usaha paham erti definisi chris...,negatif
87,2022-01-14,ekonomi,Pengumuman! Bea Keluar Cangkang Kernel Sawit T...,https://finance.detik.com/industri/d-5898920/p...,menteri uang sri mulyani indrawati turun tarif...,negatif

In [32]:
df_balanced.isna().sum()

tanggal           0
kategori          0
judul             0
url               0
konten_clean      0
sentimen_saham    0
dtype: int64

In [33]:
import pandas as pd

# pastikan kolom tanggal udah datetime
df_balanced['tanggal'] = pd.to_datetime(df_balanced['tanggal'])

# bikin full range tanggal dari 2022-01-01 sampai 2024-12-31
full_range = pd.date_range(start="2022-01-01", end="2024-12-31", freq="D")

# cek tanggal yang ga ada di df
missing_dates = full_range.difference(df_balanced['tanggal'].unique())

print("Jumlah tanggal yang kosong:", len(missing_dates))
print("Contoh tanggal kosong:", missing_dates)

Jumlah tanggal yang kosong: 14
Contoh tanggal kosong: DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-06-01', '2022-06-02', '2022-06-03', '2022-06-04',
               '2022-06-05', '2022-06-06', '2023-01-17', '2023-01-18',
               '2023-02-01', '2023-10-09'],
              dtype='datetime64[ns]', freq=None)

In [34]:
df_balanced

,tanggal,kategori,judul,url,konten_clean,sentimen_saham
8475,2024-06-08,ekonomi,"Kapan Lagi Beli AC Diskon Rp 1,3 Juta, Cuma di...",https://finance.detik.com/berita-ekonomi-bisni...,transmart full day sale hadir besok minggu 9 ...,netral
8846,2024-07-15,ekonomi,OJK Buka Suara soal Kabar Muhammadiyah Mau Cap...,https://finance.detik.com/moneter/d-7440244/oj...,organisasi muhammadiyah sorot alih dana pt ban...,netral
2031,2022-07-26,ekonomi,"Bertemu Jokowi, Xi Jinping Mau Genjot Impor Pr...",https://finance.detik.com/berita-ekonomi-bisni...,presiden joko widodo jokowi temu bilateral p...,netral
2553,2022-09-14,ekonomi,"Bicara di Forum ASEAN, Bahlil Singgung Gugatan...",https://finance.detik.com/energi/d-6292236/bic...,menteri investasi kepala badan koordinasi tana...,netral
8461,2024-06-07,ekonomi,"Transmart Banjir Diskon Produk Susu, Sampo, Sn...",https://finance.detik.com/berita-ekonomi-bisni...,transmart tawar promo tarik pekan produk cont...,netral
...,...,...,...,...,...,...
1,2022-01-05,ekonomi,"Lagi Terbelit Utang, Evergrande Disuruh Hancur...",https://finance.detik.com/properti/d-5885844/l...,selesai utang kembang properti china evergran...,negatif
2342,2022-08-25,ekonomi,Ditjen Pajak Sosialisasikan UU Cipta Kerja di ...,https://finance.detik.com/berita-ekonomi-bisni...,direktorat jenderal pajak djp perintah provi...,negatif
8636,2024-06-24,ekonomi,Petinggi Bank Dunia Respons Rencana Prabowo Pi...,https://finance.detik.com/berita-ekonomi-bisni...,perintah komando prabowo subianto-gibran rakab...,negatif
2729,2022-10-03,ekonomi,Contoh Jurnal Umum Perusahaan Dagang dan Cara ...,https://finance.detik.com/solusiukm/d-6327272/...,bahas jurnal usaha paham erti definisi chris...,negatif
87,2022-01-14,ekonomi,Pengumuman! Bea Keluar Cangkang Kernel Sawit T...,https://finance.detik.com/industri/d-5898920/p...,menteri uang sri mulyani indrawati turun tarif...,negatif

In [35]:
df_balanced = df_balanced.sort_values(by="tanggal", ascending=True).reset_index(drop=True)
df_balanced

,tanggal,kategori,judul,url,konten_clean,sentimen_saham
0,2022-01-05,ekonomi,"Ekspor Batu Bara Dilarang, Pemerintah Diminta ...",https://finance.detik.com/energi/d-5885615/eks...,krisis energi alami indonesia akibat pasok bat...,positif
1,2022-01-05,ekonomi,Perbankan Tak Bisa Mendadak Setop Biayai Batu ...,https://finance.detik.com/energi/d-5885790/per...,sektor uang perban arah dukung terap ekonomi h...,negatif
2,2022-01-05,ekonomi,"Lagi Terbelit Utang, Evergrande Disuruh Hancur...",https://finance.detik.com/properti/d-5885844/l...,selesai utang kembang properti china evergran...,negatif
3,2022-01-05,ekonomi,"Ekspor Batu Bara Dilarang, Pemerintah Diminta ...",https://finance.detik.com/energi/d-5885615/eks...,krisis energi alami indonesia akibat pasok bat...,positif
4,2022-01-05,ekonomi,Harapan Jokowi Resmikan Pasar Johar: Ekonomi R...,https://finance.detik.com/berita-ekonomi-bisni...,presiden joko widodo resmi pasar johar kota se...,netral
...,...,...,...,...,...,...
14995,2024-12-31,ekonomi,Sejarah USD (Dolar AS) Jadi Patokan Mata Uang ...,https://finance.detik.com/berita-ekonomi-bisni...,zaman emas patok mata uang anggap milik nilai...,positif
14996,2024-12-31,ekonomi,Wamentan Sudaryono atau yang akrab disapa Mas ...,https://finance.detik.com/berita-ekonomi-bisni...,wamentan sudaryono akrab sapa ma dar sedia be...,positif
14997,2024-12-31,ekonomi,Kemendag mempunyai sembilan gudang SRG dan sat...,https://finance.detik.com/berita-ekonomi-bisni...,kemendag sembilan gudang srg gudang sistem con...,positif
14998,2024-12-31,ekonomi,Sejarah USD (Dolar AS) Jadi Patokan Mata Uang ...,https://finance.detik.com/berita-ekonomi-bisni...,zaman emas patok mata uang anggap milik nilai...,positif
14999,2024-12-31,ekonomi,Hal tersebut disampaikan oleh Direktur Jendera...,https://finance.detik.com/energi/d-7712214/kad...,direktur jenderal ketenagalistrikan menteri en...,positif

In [106]:
df_balanced.to_csv("ALL_DATA_BERITA_BALANCING5000.csv")