In [ ]:
import pandas as pd

df = pd.read_csv('FEW_ONLY_DATA_BERITA_FIX.csv')
df

,Unnamed: 0,tanggal,kategori,judul,url,konten_clean
0,0,2022-01-03,ekonomi,Juragan Batu Bara RI,https://finance.detik.com/infografis/d-5882815...,bijak sayang usaha usaha nilai bijak buru b...
1,1,2022-01-03,ekonomi,"PLN Dapat Tambahan 3,2 Juta Ton Batu Bara Imba...",https://finance.detik.com/energi/d-5882841/pln...,perintah setop ekspor batu bara penuh butuh ne...
2,2,2022-01-03,ekonomi,"Pusat Kucurkan Rp 2,1 T ke Pemprov DKI demi Ce...",https://finance.detik.com/infrastruktur/d-5882...,gubernur dki jakarta anies baswedan terima dan...
3,3,2022-01-03,ekonomi,5 Profesi Paling Diburu di 2022,https://finance.detik.com/infografis/d-5882813...,orang lomba cari kerja industri rugi imbas p...
4,4,2022-01-03,ekonomi,"Ekspor Batu Bara Disetop, Kocek Negara Terganggu?",https://finance.detik.com/energi/d-5882796/eks...,perintah setop ekspor batu bara penuh butuh ne...
...,...,...,...,...,...,...
237,237,2023-02-01,ekonomi,Pengguna Mobile Banking BNI hingga BNIDirect T...,https://finance.detik.com/moneter/d-6546635/pe...,pt bank negara indonesia persero tbk kembang...
238,238,2023-02-01,ekonomi,"Prospek Bisnis Pengiriman Barang, Masihkah Cer...",https://finance.detik.com/berita-ekonomi-bisni...,perintah resmi cabut laku batas giat masyaraka...
239,239,2023-02-01,ekonomi,Nasib Freeport Masih Abu-abu di Tengah Rencana...,https://finance.detik.com/energi/d-6546561/nas...,perintah putus nasib pt freeport indonesia lar...
240,240,2023-02-01,ekonomi,"BSI Mau Caplok BTN Syariah, Begini Progresnya",https://finance.detik.com/moneter/d-6546568/bs...,unit usaha syariah uus pt bank tabung negara...
241,241,2023-02-01,ekonomi,"Laba Bersih BSI Tembus Rp 4,26 T, Meroket 40,68%",https://finance.detik.com/bursa-dan-valas/d-65...,pt bank syariah indonesia tbk bsi periode 20...

In [ ]:
saham_keywords = [
    "saham", "ihsg", "bursa", "bei", "emiten", "investor", "investasi", "pasar modal",
    "ipo", "dividen", "rupiah", "kurs", "obligasi", "indeks", "ekonomi", "perdagangan",
    "market", "harga", "komoditas", "delisting", "suspensi perdagangan", "listing",
    "volatility", "kapitalisasi", "suku bunga", "inflasi", "perekonomian",
    "defisit", "surplus"
]

In [ ]:
import re

pattern = re.compile(r'\b(?:' + '|'.join(saham_keywords) + r')\b', flags=re.IGNORECASE)

In [ ]:
df.isna().sum()

Unnamed: 0      0
tanggal         0
kategori        0
judul           0
url             0
konten_clean    0
dtype: int64

In [ ]:
mask = df['judul'].str.contains(pattern, na=False) | df['konten_clean'].str.contains(pattern, na=False)
berita_saham = df[mask]

In [ ]:
berita_saham

,Unnamed: 0,tanggal,kategori,judul,url,konten_clean
2,2,2022-01-03,ekonomi,"Pusat Kucurkan Rp 2,1 T ke Pemprov DKI demi Ce...",https://finance.detik.com/infrastruktur/d-5882...,gubernur dki jakarta anies baswedan terima dan...
4,4,2022-01-03,ekonomi,"Ekspor Batu Bara Disetop, Kocek Negara Terganggu?",https://finance.detik.com/energi/d-5882796/eks...,perintah setop ekspor batu bara penuh butuh ne...
5,5,2022-01-03,ekonomi,Kala Jokowi sampai Sri Mulyani Waswas Dampak O...,https://finance.detik.com/berita-ekonomi-bisni...,presiden joko widodo deret tantang sektor ekon...
7,7,2022-01-03,ekonomi,Jokowi Perintahkan Mendag Bikin Harga Minyak G...,https://finance.detik.com/berita-ekonomi-bisni...,presiden joko widodo jokowi perintah menteri...
8,8,2022-01-03,ekonomi,Keras! Jokowi Ancam Cabut Izin Produsen Batu B...,https://finance.detik.com/berita-ekonomi-bisni...,presiden joko widodo segan sanksi cabut izin e...
...,...,...,...,...,...,...
236,236,2023-02-01,ekonomi,Jumlah Bandara Internasional di RI Bakal Dipan...,https://finance.detik.com/infrastruktur/d-6546...,menteri bumn erick thohir beber hasil rapat pr...
237,237,2023-02-01,ekonomi,Pengguna Mobile Banking BNI hingga BNIDirect T...,https://finance.detik.com/moneter/d-6546635/pe...,pt bank negara indonesia persero tbk kembang...
239,239,2023-02-01,ekonomi,Nasib Freeport Masih Abu-abu di Tengah Rencana...,https://finance.detik.com/energi/d-6546561/nas...,perintah putus nasib pt freeport indonesia lar...
240,240,2023-02-01,ekonomi,"BSI Mau Caplok BTN Syariah, Begini Progresnya",https://finance.detik.com/moneter/d-6546568/bs...,unit usaha syariah uus pt bank tabung negara...
241,241,2023-02-01,ekonomi,"Laba Bersih BSI Tembus Rp 4,26 T, Meroket 40,68%",https://finance.detik.com/bursa-dan-valas/d-65...,pt bank syariah indonesia tbk bsi periode 20...

In [ ]:
print("jumlah data awal", len(df))
print("jumlah berita saham", len(berita_saham))

jumlah data awal 242
jumlah berita saham 170

In [ ]:
berita_saham.isna().sum()

Unnamed: 0      0
tanggal         0
kategori        0
judul           0
url             0
konten_clean    0
dtype: int64

In [ ]:
berita_saham.to_csv("ALL_SAHAM_RELEVANCY_NEWS2.csv")

In [ ]:
df=pd.read_csv("ALL_SAHAM_RELEVANCY_NEWS2.csv")
df

,Unnamed: 0.1,Unnamed: 0,tanggal,kategori,judul,url,konten_clean
0,2,2,2022-01-03,ekonomi,"Pusat Kucurkan Rp 2,1 T ke Pemprov DKI demi Ce...",https://finance.detik.com/infrastruktur/d-5882...,gubernur dki jakarta anies baswedan terima dan...
1,4,4,2022-01-03,ekonomi,"Ekspor Batu Bara Disetop, Kocek Negara Terganggu?",https://finance.detik.com/energi/d-5882796/eks...,perintah setop ekspor batu bara penuh butuh ne...
2,5,5,2022-01-03,ekonomi,Kala Jokowi sampai Sri Mulyani Waswas Dampak O...,https://finance.detik.com/berita-ekonomi-bisni...,presiden joko widodo deret tantang sektor ekon...
3,7,7,2022-01-03,ekonomi,Jokowi Perintahkan Mendag Bikin Harga Minyak G...,https://finance.detik.com/berita-ekonomi-bisni...,presiden joko widodo jokowi perintah menteri...
4,8,8,2022-01-03,ekonomi,Keras! Jokowi Ancam Cabut Izin Produsen Batu B...,https://finance.detik.com/berita-ekonomi-bisni...,presiden joko widodo segan sanksi cabut izin e...
...,...,...,...,...,...,...,...
165,236,236,2023-02-01,ekonomi,Jumlah Bandara Internasional di RI Bakal Dipan...,https://finance.detik.com/infrastruktur/d-6546...,menteri bumn erick thohir beber hasil rapat pr...
166,237,237,2023-02-01,ekonomi,Pengguna Mobile Banking BNI hingga BNIDirect T...,https://finance.detik.com/moneter/d-6546635/pe...,pt bank negara indonesia persero tbk kembang...
167,239,239,2023-02-01,ekonomi,Nasib Freeport Masih Abu-abu di Tengah Rencana...,https://finance.detik.com/energi/d-6546561/nas...,perintah putus nasib pt freeport indonesia lar...
168,240,240,2023-02-01,ekonomi,"BSI Mau Caplok BTN Syariah, Begini Progresnya",https://finance.detik.com/moneter/d-6546568/bs...,unit usaha syariah uus pt bank tabung negara...
169,241,241,2023-02-01,ekonomi,"Laba Bersih BSI Tembus Rp 4,26 T, Meroket 40,68%",https://finance.detik.com/bursa-dan-valas/d-65...,pt bank syariah indonesia tbk bsi periode 20...

In [ ]:
!pip install -q transformers torch pandas

import pandas as pd
import re
import torch
from transformers import pipeline, AutoTokenizer, AutoModelForSequenceClassification

# ========== 1. Load model & tokenizer yang benar ==========
MODEL_ID = "taufiqdp/indonesian-sentiment"  # ini model yang tersedia publik :contentReference[oaicite:1]{index=1}

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
model = AutoModelForSequenceClassification.from_pretrained(MODEL_ID)

print("Label mapping (id2label):", model.config.id2label)

device = 0 if torch.cuda.is_available() else -1
sentiment_pipe = pipeline(
    "text-classification",
    model=model,
    tokenizer=tokenizer,
    device=device,
    return_all_scores=False
)

Device set to use cpu

Label mapping (id2label): {0: 'negatif', 1: 'netral', 2: 'positif'}

/usr/local/lib/python3.12/dist-packages/transformers/pipelines/text_classification.py:111: UserWarning: `return_all_scores` is now deprecated,  if want a similar functionality use `top_k=None` instead of `return_all_scores=True` or `top_k=1` instead of `return_all_scores=False`.
  warnings.warn(

In [ ]:
# ========== 2. Fungsi batch prediksi ==========
def predict_batch(texts, batch_size=32):
    results = []
    for i in range(0, len(texts), batch_size):
        batch = texts[i : i + batch_size]
        preds = sentiment_pipe(batch, truncation=True, max_length=512)
        results.extend(preds)
    return results

In [ ]:
# ========== 3. Keyword saham vs override ==========
positif_keywords = [
    "menguat", "rebound", "bullish", "surplus", "naik", "melonjak",
    "penguatan", "stabil", "optimis", "pulih", "rekor", "melambung"
]
negatif_keywords = [
    "melemah", "anjlok", "bearish", "defisit", "turun", "merosot",
    "penurunan", "tertekan", "resesi", "krisis", "minus", "collapse", "pelemahan"
]

positif_pattern = re.compile(r"\b(" + "|".join(positif_keywords) + r")\b", re.IGNORECASE)
negatif_pattern = re.compile(r"\b(" + "|".join(negatif_keywords) + r")\b", re.IGNORECASE)

def apply_keyword_override(text, model_label, model_score):
    pos_match = bool(positif_pattern.search(text))
    neg_match = bool(negatif_pattern.search(text))

    if pos_match and not neg_match:
        return "positif", 1.0
    elif neg_match and not pos_match:
        return "negatif", 1.0
    elif pos_match and neg_match:
        # kalau kedua jenis keyword ada, pilih berdasarkan jumlah kemunculan
        pos_count = len(positif_pattern.findall(text))
        neg_count = len(negatif_pattern.findall(text))
        if pos_count > neg_count:
            return "positif", 1.0
        elif neg_count > pos_count:
            return "negatif", 1.0
        else:
            # seimbang → fallback ke hasil model
            return model_label, model_score
    else:
        # tidak ada keyword → pake hasil model
        return model_label, model_score

In [ ]:
# ========== 4. Proses DataFrame ==========
# Pastikan kamu punya DataFrame `df` dan ada kolom teks, misalnya “konten_clean”
df["konten_clean"] = df["konten_clean"].fillna("").astype(str)

preds = predict_batch(df["konten_clean"].tolist(), batch_size=32)
df["sentiment_label_model"] = [p["label"] for p in preds]
df["sentiment_score_model"] = [float(p["score"]) for p in preds]

# Model memberikan label default seperti "NEGATIVE", "NEUTRAL", "POSITIVE" atau tergantung id2label
# Kita bisa peta label ke bahasa Indonesia kalau ingin:
# Misal id2label = {0: "negative", 1: "neutral", 2: "positive"}
# Pastikan model.config.id2label terlebih dahulu

# Jika id2label mapping dalam bahasa Inggris, ubah ke bahasa Indonesia:
mapping = {}
for idx, lbl in model.config.id2label.items():
    lbl_low = lbl.lower()
    if "neg" in lbl_low:
        mapping[lbl] = "negatif"
    elif "neu" in lbl_low:
        mapping[lbl] = "netral"
    elif "pos" in lbl_low:
        mapping[lbl] = "positif"
    else:
        mapping[lbl] = lbl  # fallback

# Ubah label model ke versi Indonesia
df["sentiment_label_model_id"] = df["sentiment_label_model"].map(mapping).fillna(df["sentiment_label_model"])

# override keyword
adjusted = [
    apply_keyword_override(text, lbl_id, scr)
    for text, lbl_id, scr in zip(df["konten_clean"],
                                 df["sentiment_label_model_id"],
                                 df["sentiment_score_model"])
]
df["sentiment_label"], df["sentiment_score"] = zip(*adjusted)

In [ ]:
# ========== 5. Simpan + cek distribusi ==========
df.to_csv("df_sentiment_saham_taufiqdp2.csv", index=False)
print("Selesai — file ditulis: df_sentiment_saham_taufiqdp.csv")
print("Distribusi sentiment_label:", df["sentiment_label"].value_counts())

Selesai — file ditulis: df_sentiment_saham_taufiqdp.csv
Distribusi sentiment_label: sentiment_label
netral     70
positif    67
negatif    33
Name: count, dtype: int64

In [ ]:
df=pd.read_csv("df_sentiment_saham_taufiqdp2.csv")
df

,Unnamed: 0.1,Unnamed: 0,tanggal,kategori,judul,url,konten_clean,sentiment_label_model,sentiment_score_model,sentiment_label_model_id,sentiment_label,sentiment_score
0,2,2,2022-01-03,ekonomi,"Pusat Kucurkan Rp 2,1 T ke Pemprov DKI demi Ce...",https://finance.detik.com/infrastruktur/d-5882...,gubernur dki jakarta anies baswedan terima dan...,netral,0.902250,netral,negatif,1.000000
1,4,4,2022-01-03,ekonomi,"Ekspor Batu Bara Disetop, Kocek Negara Terganggu?",https://finance.detik.com/energi/d-5882796/eks...,perintah setop ekspor batu bara penuh butuh ne...,netral,0.972876,netral,netral,0.972876
2,5,5,2022-01-03,ekonomi,Kala Jokowi sampai Sri Mulyani Waswas Dampak O...,https://finance.detik.com/berita-ekonomi-bisni...,presiden joko widodo deret tantang sektor ekon...,netral,0.644876,netral,netral,0.644876
3,7,7,2022-01-03,ekonomi,Jokowi Perintahkan Mendag Bikin Harga Minyak G...,https://finance.detik.com/berita-ekonomi-bisni...,presiden joko widodo jokowi perintah menteri...,netral,0.680815,netral,netral,0.680815
4,8,8,2022-01-03,ekonomi,Keras! Jokowi Ancam Cabut Izin Produsen Batu B...,https://finance.detik.com/berita-ekonomi-bisni...,presiden joko widodo segan sanksi cabut izin e...,netral,0.720792,netral,netral,0.720792
...,...,...,...,...,...,...,...,...,...,...,...,...
165,236,236,2023-02-01,ekonomi,Jumlah Bandara Internasional di RI Bakal Dipan...,https://finance.detik.com/infrastruktur/d-6546...,menteri bumn erick thohir beber hasil rapat pr...,netral,0.730054,netral,netral,0.730054
166,237,237,2023-02-01,ekonomi,Pengguna Mobile Banking BNI hingga BNIDirect T...,https://finance.detik.com/moneter/d-6546635/pe...,pt bank negara indonesia persero tbk kembang...,netral,0.906520,netral,netral,0.906520
167,239,239,2023-02-01,ekonomi,Nasib Freeport Masih Abu-abu di Tengah Rencana...,https://finance.detik.com/energi/d-6546561/nas...,perintah putus nasib pt freeport indonesia lar...,positif,0.509565,positif,positif,0.509565
168,240,240,2023-02-01,ekonomi,"BSI Mau Caplok BTN Syariah, Begini Progresnya",https://finance.detik.com/moneter/d-6546568/bs...,unit usaha syariah uus pt bank tabung negara...,positif,0.801213,positif,positif,1.000000
169,241,241,2023-02-01,ekonomi,"Laba Bersih BSI Tembus Rp 4,26 T, Meroket 40,68%",https://finance.detik.com/bursa-dan-valas/d-65...,pt bank syariah indonesia tbk bsi periode 20...,positif,0.578355,positif,positif,1.000000

In [ ]:
df=df.drop(columns=["Unnamed: 0", "Unnamed: 0.1"])
df.head()

,tanggal,kategori,judul,url,konten_clean,sentiment_label_model,sentiment_score_model,sentiment_label_model_id,sentiment_label,sentiment_score
0,2022-01-03,ekonomi,"Pusat Kucurkan Rp 2,1 T ke Pemprov DKI demi Ce...",https://finance.detik.com/infrastruktur/d-5882...,gubernur dki jakarta anies baswedan terima dan...,netral,0.902250,netral,negatif,1.000000
1,2022-01-03,ekonomi,"Ekspor Batu Bara Disetop, Kocek Negara Terganggu?",https://finance.detik.com/energi/d-5882796/eks...,perintah setop ekspor batu bara penuh butuh ne...,netral,0.972876,netral,netral,0.972876
2,2022-01-03,ekonomi,Kala Jokowi sampai Sri Mulyani Waswas Dampak O...,https://finance.detik.com/berita-ekonomi-bisni...,presiden joko widodo deret tantang sektor ekon...,netral,0.644876,netral,netral,0.644876
3,2022-01-03,ekonomi,Jokowi Perintahkan Mendag Bikin Harga Minyak G...,https://finance.detik.com/berita-ekonomi-bisni...,presiden joko widodo jokowi perintah menteri...,netral,0.680815,netral,netral,0.680815
4,2022-01-03,ekonomi,Keras! Jokowi Ancam Cabut Izin Produsen Batu B...,https://finance.detik.com/berita-ekonomi-bisni...,presiden joko widodo segan sanksi cabut izin e...,netral,0.720792,netral,netral,0.720792

In [ ]:
df.sentiment_label.value_counts()

sentiment_label
netral     70
positif    67
negatif    33
Name: count, dtype: int64

In [ ]:
df.isna().sum()

tanggal                     0
kategori                    0
judul                       0
url                         0
konten_clean                0
sentiment_label_model       0
sentiment_score_model       0
sentiment_label_model_id    0
sentiment_label             0
sentiment_score             0
dtype: int64

In [ ]:
from sklearn.utils import resample

# Pisahkan per kelas
df_pos = df[df["sentiment_label"] == "positif"]
df_net = df[df["sentiment_label"] == "netral"]
df_neg = df[df["sentiment_label"] == "negatif"]

# Target jumlah
TARGET = 60

# Resampling
df_pos_bal = resample(df_pos, replace=False, n_samples=TARGET, random_state=42)  # undersample
df_net_bal = resample(df_net, replace=False, n_samples=TARGET, random_state=42)  # undersample
df_neg_bal = resample(df_neg, replace=True,  n_samples=TARGET, random_state=42)  # oversample

# Gabung lagi
df_balanced = pd.concat([df_pos_bal, df_net_bal, df_neg_bal])

# Shuffle biar acak
df_balanced = df_balanced.sample(frac=1, random_state=42).reset_index(drop=True)

In [ ]:
df_balanced.to_csv("df_sentiment_saham_balanced2.csv", index=False)
print("Selesai — data balanced disimpan ke df_sentiment_saham_balanced.csv")
print("Distribusi baru:")
print(df_balanced["sentiment_label"].value_counts())

Selesai — data balanced disimpan ke df_sentiment_saham_balanced.csv
Distribusi baru:
sentiment_label
positif    60
negatif    60
netral     60
Name: count, dtype: int64

In [ ]:
df=pd.read_csv("df_sentiment_saham_balanced2.csv")
df

,tanggal,kategori,judul,url,konten_clean,sentiment_label_model,sentiment_score_model,sentiment_label_model_id,sentiment_label,sentiment_score
0,2022-06-03,ekonomi,"Subsidi ke Pertamina Nambah, Harga Pertalite-L...",https://finance.detik.com/energi/d-6109535/sub...,pertamina tambah subsidi bbm lpg apbn 2022 bel...,netral,0.747786,netral,positif,1.000000
1,2022-06-03,ekonomi,"Harta LeBron James Tembus US$ 1 Miliar, Resmi ...",https://finance.detik.com/berita-ekonomi-bisni...,main bola basket kenal amerika serikat lebron ...,positif,0.495341,positif,positif,0.495341
2,2022-01-04,ekonomi,"Di RI Booming Boneka Arwah, Jepang Malah Gandr...",https://finance.detik.com/berita-ekonomi-bisni...,masyarakat indonesia heboh spirit doll boneka ...,negatif,0.558344,negatif,negatif,0.558344
3,2023-01-19,ekonomi,Cerita Erick Thohir soal Bahlil yang Sempat Di...,https://finance.detik.com/berita-ekonomi-bisni...,menteri bumn erick thohir cerita menteri inves...,netral,0.920338,netral,netral,0.920338
4,2022-01-03,ekonomi,"Pusat Kucurkan Rp 2,1 T ke Pemprov DKI demi Ce...",https://finance.detik.com/infrastruktur/d-5882...,gubernur dki jakarta anies baswedan terima dan...,netral,0.902250,netral,negatif,1.000000
...,...,...,...,...,...,...,...,...,...,...
175,2022-01-03,ekonomi,Jokowi Perintahkan Mendag Bikin Harga Minyak G...,https://finance.detik.com/berita-ekonomi-bisni...,presiden joko widodo jokowi perintah menteri...,netral,0.680815,netral,netral,0.680815
176,2022-06-02,ekonomi,Bea Cukai Beri Insentif Fiskal untuk Dukung In...,https://finance.detik.com/berita-ekonomi-bisni...,bea cukai insentif fiskal fasilitas pabean li...,netral,0.974483,netral,netral,0.974483
177,2023-02-01,ekonomi,"Laba Bersih BSI Tembus Rp 4,26 T, Meroket 40,68%",https://finance.detik.com/bursa-dan-valas/d-65...,pt bank syariah indonesia tbk bsi periode 20...,positif,0.578355,positif,positif,1.000000
178,2022-06-02,ekonomi,3 Fakta Beli Solar dan Pertalite Harus Pakai A...,https://finance.detik.com/energi/d-6107306/3-f...,perintah atur beli solar subsidi pertalite at...,netral,0.978355,netral,netral,0.978355
179,2023-02-01,ekonomi,Jumlah Bandara Internasional di RI Bakal Dipan...,https://finance.detik.com/infrastruktur/d-6546...,menteri bumn erick thohir beber hasil rapat pr...,netral,0.730054,netral,netral,0.730054

In [ ]:
df= df[[
    "tanggal", "kategori", "judul", "url",
    "konten_clean", "sentiment_label", "sentiment_score"
]]

In [ ]:
df

,tanggal,kategori,judul,url,konten_clean,sentiment_label,sentiment_score
0,2022-06-03,ekonomi,"Subsidi ke Pertamina Nambah, Harga Pertalite-L...",https://finance.detik.com/energi/d-6109535/sub...,pertamina tambah subsidi bbm lpg apbn 2022 bel...,positif,1.000000
1,2022-06-03,ekonomi,"Harta LeBron James Tembus US$ 1 Miliar, Resmi ...",https://finance.detik.com/berita-ekonomi-bisni...,main bola basket kenal amerika serikat lebron ...,positif,0.495341
2,2022-01-04,ekonomi,"Di RI Booming Boneka Arwah, Jepang Malah Gandr...",https://finance.detik.com/berita-ekonomi-bisni...,masyarakat indonesia heboh spirit doll boneka ...,negatif,0.558344
3,2023-01-19,ekonomi,Cerita Erick Thohir soal Bahlil yang Sempat Di...,https://finance.detik.com/berita-ekonomi-bisni...,menteri bumn erick thohir cerita menteri inves...,netral,0.920338
4,2022-01-03,ekonomi,"Pusat Kucurkan Rp 2,1 T ke Pemprov DKI demi Ce...",https://finance.detik.com/infrastruktur/d-5882...,gubernur dki jakarta anies baswedan terima dan...,negatif,1.000000
...,...,...,...,...,...,...,...
175,2022-01-03,ekonomi,Jokowi Perintahkan Mendag Bikin Harga Minyak G...,https://finance.detik.com/berita-ekonomi-bisni...,presiden joko widodo jokowi perintah menteri...,netral,0.680815
176,2022-06-02,ekonomi,Bea Cukai Beri Insentif Fiskal untuk Dukung In...,https://finance.detik.com/berita-ekonomi-bisni...,bea cukai insentif fiskal fasilitas pabean li...,netral,0.974483
177,2023-02-01,ekonomi,"Laba Bersih BSI Tembus Rp 4,26 T, Meroket 40,68%",https://finance.detik.com/bursa-dan-valas/d-65...,pt bank syariah indonesia tbk bsi periode 20...,positif,1.000000
178,2022-06-02,ekonomi,3 Fakta Beli Solar dan Pertalite Harus Pakai A...,https://finance.detik.com/energi/d-6107306/3-f...,perintah atur beli solar subsidi pertalite at...,netral,0.978355
179,2023-02-01,ekonomi,Jumlah Bandara Internasional di RI Bakal Dipan...,https://finance.detik.com/infrastruktur/d-6546...,menteri bumn erick thohir beber hasil rapat pr...,netral,0.730054

In [ ]:
df.sentiment_label.value_counts()

sentiment_label
positif    60
negatif    60
netral     60
Name: count, dtype: int64

In [ ]:
df.to_csv("df_few_sentiment_balanced_final.csv", index=False)

In [ ]:
import pandas as pd

# Load data saham yang sudah dibersihkan
df_saham = pd.read_csv("DATA_SAHAM_22-24_CLEAN.csv")
df_saham["tanggal"] = pd.to_datetime(df_saham["tanggal"], errors="coerce")

# Load data sentimen yang sudah dibalance
df_sentimen = pd.read_csv("df_sentiment_saham_balanced.csv")
df_sentimen["tanggal"] = pd.to_datetime(df_sentimen["tanggal"], errors="coerce")

# --- Agregasi sentimen per tanggal ---
agg_sentimen = df_sentimen.groupby("tanggal").agg(
    avg_sentiment=("sentiment_score", "mean"),
    prop_pos=("sentiment_label", lambda x: (x=="positif").mean()),
    prop_neg=("sentiment_label", lambda x: (x=="negatif").mean()),
    max_impact=("sentiment_label", lambda x: x.value_counts().idxmax())
).reset_index()

# --- Merge ke data saham ---
df_final = pd.merge(df_saham, agg_sentimen, on="tanggal", how="left")

print("Data akhir:", df_final.shape)
df_final

Data akhir: (725, 11)

,tanggal,Terakhir,Pembukaan,Tertinggi,Terendah,Vol.,Perubahan%,avg_sentiment,prop_pos,prop_neg,max_impact
0,2022-01-03,666531.0,658626.0,667720.0,658613.0,1.826000e+10,1.27,0.834439,0.16,0.36,netral
1,2022-01-04,669537.0,667513.0,672066.0,667513.0,1.859000e+10,0.45,0.814955,0.44,0.36,positif
2,2022-01-05,666230.0,670317.0,673811.0,663484.0,1.791000e+10,-0.49,NaN,NaN,NaN,NaN
3,2022-01-06,665335.0,667485.0,667985.0,659323.0,1.800000e+10,-0.13,NaN,NaN,NaN,NaN
4,2022-01-07,670132.0,666951.0,671215.0,664771.0,1.571000e+10,0.72,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
720,2024-12-20,698387.0,698017.0,703240.0,693158.0,1.457000e+10,0.09,NaN,NaN,NaN,NaN
721,2024-12-23,709644.0,703753.0,709644.0,703573.0,1.387000e+10,1.61,NaN,NaN,NaN,NaN
722,2024-12-24,706575.0,711564.0,712058.0,706375.0,1.106000e+10,-0.43,NaN,NaN,NaN,NaN
723,2024-12-27,703657.0,707338.0,710027.0,702471.0,1.443000e+10,-0.41,NaN,NaN,NaN,NaN
724,2024-12-30,707990.0,702678.0,707990.0,699307.0,1.597000e+10,0.62,NaN,NaN,NaN,NaN

In [ ]:
def categorize_sentiment(score, pos_thresh=0.6, neg_thresh=0.4):
    if pd.isna(score):
        return "tidak ada data"
    elif score >= pos_thresh:
        return "positif"
    elif score <= neg_thresh:
        return "negatif"
    else:
        return "netral"

In [ ]:
df_final["avg_sentiment_result"] = df_final["avg_sentiment"].apply(categorize_sentiment)

In [ ]:
df_final

,tanggal,Terakhir,Pembukaan,Tertinggi,Terendah,Vol.,Perubahan%,avg_sentiment,prop_pos,prop_neg,max_impact,avg_sentiment_result
0,2022-01-03,666531.0,658626.0,667720.0,658613.0,1.826000e+10,1.27,0.834439,0.16,0.36,netral,positif
1,2022-01-04,669537.0,667513.0,672066.0,667513.0,1.859000e+10,0.45,0.814955,0.44,0.36,positif,positif
2,2022-01-05,666230.0,670317.0,673811.0,663484.0,1.791000e+10,-0.49,NaN,NaN,NaN,NaN,tidak ada data
3,2022-01-06,665335.0,667485.0,667985.0,659323.0,1.800000e+10,-0.13,NaN,NaN,NaN,NaN,tidak ada data
4,2022-01-07,670132.0,666951.0,671215.0,664771.0,1.571000e+10,0.72,NaN,NaN,NaN,NaN,tidak ada data
...,...,...,...,...,...,...,...,...,...,...,...,...
720,2024-12-20,698387.0,698017.0,703240.0,693158.0,1.457000e+10,0.09,NaN,NaN,NaN,NaN,tidak ada data
721,2024-12-23,709644.0,703753.0,709644.0,703573.0,1.387000e+10,1.61,NaN,NaN,NaN,NaN,tidak ada data
722,2024-12-24,706575.0,711564.0,712058.0,706375.0,1.106000e+10,-0.43,NaN,NaN,NaN,NaN,tidak ada data
723,2024-12-27,703657.0,707338.0,710027.0,702471.0,1.443000e+10,-0.41,NaN,NaN,NaN,NaN,tidak ada data
724,2024-12-30,707990.0,702678.0,707990.0,699307.0,1.597000e+10,0.62,NaN,NaN,NaN,NaN,tidak ada data

In [ ]:
# Simpan hasil gabungan
df_final.to_csv("ihsg_sentimen_features2.csv", index=False)

In [ ]:
df=pd.read_csv("FEW_ONLY_DATA_BERITA_FIX2.csv")
df

,Unnamed: 0,tanggal,kategori,judul,url,konten_clean
0,0,2023-01-17,ekonomi,RI Restui 'Raksasa' Migas Italia Garap Proyek ...,https://finance.detik.com/energi/d-6521073/ri-...,perintah tuju rencana kembang lapang plan of d...
1,1,2023-01-17,ekonomi,RI Butuh Investasi Rp 8.280 T buat Genjot Hili...,https://finance.detik.com/berita-ekonomi-bisni...,menteri investasi kepala badan koordinasi tana...
2,2,2023-01-17,ekonomi,"Soal Bentrok di PT GNI, Bahlil: Jangan Digemba...",https://finance.detik.com/industri/d-6521033/s...,menteri investasi kepala badan koordinasi tana...
3,3,2023-01-17,ekonomi,Tencent Pecat 100 Koruptor di Internal Perusahaan,https://finance.detik.com/berita-ekonomi-bisni...,tencent holding usaha gim digital asl china g...
4,4,2023-01-17,ekonomi,"Banyak Hotel Dijual Usai Pandemi, Pengusaha Un...",https://finance.detik.com/properti/d-6520841/b...,hotel jual situs jual beli online ketua bpd ...
5,5,2023-01-17,ekonomi,"Kementerian PUPR Mau Lelang Proyek IKN Rp 23,7...",https://finance.detik.com/properti/d-6520952/k...,menteri kerja rumah rakyat pupr lelang 30 pa...
6,6,2023-01-17,ekonomi,Kepala BIN Beberkan Sederet Faktor Pemicu 2023...,https://finance.detik.com/berita-ekonomi-bisni...,kepala badan intelijen negara bin budi gunaw...
7,7,2023-01-17,ekonomi,Sandiaga Uno Usul Hari Kejepit Jadi Libur Bers...,https://finance.detik.com/berita-ekonomi-bisni...,menteri pariwisata ekonomi kreatif menparekr...
8,8,2023-01-17,ekonomi,Terkuak! 2 Alasan Produsen Sepatu Merek Dunia ...,https://finance.detik.com/berita-ekonomi-bisni...,produsen sepatu merek dunia serang banten pt...
9,9,2023-01-17,ekonomi,"Proyek Tol Terpanjang di RI Dilelang Ulang, Pe...",https://finance.detik.com/infrastruktur/d-6520...,bangun tol gedebage-tasikmalaya-cilacap getac...
10,10,2023-01-17,ekonomi,"Bayar Tol Tanpa Setop Baru Mau Uji Coba Maret,...",https://finance.detik.com/infrastruktur/d-6520...,menteri kerja rumah rakyat pupr uji coba sis...
11,11,2023-01-17,ekonomi,Menteri PUPR Tegaskan Moge Tidak Bisa Masuk To...,https://finance.detik.com/infrastruktur/d-6520...,komunitas motor club indonesia mbci motor ge...
12,12,2023-01-17,ekonomi,RI Restui 'Raksasa' Migas Italia Garap Proyek ...,https://finance.detik.com/energi/d-6521073/ri-...,perintah tuju rencana kembang lapang plan of d...
13,13,2023-01-17,ekonomi,RI Butuh Investasi Rp 8.280 T buat Genjot Hili...,https://finance.detik.com/berita-ekonomi-bisni...,menteri investasi kepala badan koordinasi tana...
14,14,2023-01-17,ekonomi,"Soal Bentrok di PT GNI, Bahlil: Jangan Digemba...",https://finance.detik.com/industri/d-6521033/s...,menteri investasi kepala badan koordinasi tana...
15,15,2023-01-17,ekonomi,Tencent Pecat 100 Koruptor di Internal Perusahaan,https://finance.detik.com/berita-ekonomi-bisni...,tencent holding usaha gim digital asl china g...
16,16,2023-01-17,ekonomi,"Banyak Hotel Dijual Usai Pandemi, Pengusaha Un...",https://finance.detik.com/properti/d-6520841/b...,hotel jual situs jual beli online ketua bpd ...
17,17,2023-01-17,ekonomi,"Kementerian PUPR Mau Lelang Proyek IKN Rp 23,7...",https://finance.detik.com/properti/d-6520952/k...,menteri kerja rumah rakyat pupr lelang 30 pa...
18,18,2023-01-17,ekonomi,Kepala BIN Beberkan Sederet Faktor Pemicu 2023...,https://finance.detik.com/berita-ekonomi-bisni...,kepala badan intelijen negara bin budi gunaw...
19,19,2023-01-17,ekonomi,Sandiaga Uno Usul Hari Kejepit Jadi Libur Bers...,https://finance.detik.com/berita-ekonomi-bisni...,menteri pariwisata ekonomi kreatif menparekr...
20,20,2023-01-17,ekonomi,Terkuak! 2 Alasan Produsen Sepatu Merek Dunia ...,https://finance.detik.com/berita-ekonomi-bisni...,produsen sepatu merek dunia serang banten pt...
21,21,2023-01-17,ekonomi,"Proyek Tol Terpanjang di RI Dilelang Ulang, Pe...",https://finance.detik.com/infrastruktur/d-6520...,bangun tol gedebage-tasikmalaya-cilacap getac...
22,22,2023-01-17,ekonomi,"Bayar Tol Tanpa Setop Baru Mau Uji Coba Maret,...",https://finance.detik.com/infrastruktur/d-6520...,menteri kerja rumah rakyat pupr uji coba sis...
23,23,2023-01-17,ekonomi,Menteri PUPR Tegaskan Moge Tidak Bisa Masuk To...,https://finance.detik.com/infrastruktur/d-6520...,komunitas motor club indonesia mbci motor ge...

In [ ]:
saham_keywords = [
    "saham", "ihsg", "bursa", "bei", "emiten", "investor", "investasi", "pasar modal",
    "ipo", "dividen", "rupiah", "kurs", "obligasi", "indeks", "ekonomi", "perdagangan",
    "market", "harga", "komoditas", "delisting", "suspensi perdagangan", "listing",
    "volatility", "kapitalisasi", "suku bunga", "inflasi", "perekonomian",
    "defisit", "surplus"
]

In [ ]:
import re

pattern = re.compile(r'\b(?:' + '|'.join(saham_keywords) + r')\b', flags=re.IGNORECASE)

In [ ]:
mask = df['judul'].str.contains(pattern, na=False) | df['konten_clean'].str.contains(pattern, na=False)
berita_saham = df[mask]

In [ ]:
berita_saham

,Unnamed: 0,tanggal,kategori,judul,url,konten_clean
1,1,2023-01-17,ekonomi,RI Butuh Investasi Rp 8.280 T buat Genjot Hili...,https://finance.detik.com/berita-ekonomi-bisni...,menteri investasi kepala badan koordinasi tana...
2,2,2023-01-17,ekonomi,"Soal Bentrok di PT GNI, Bahlil: Jangan Digemba...",https://finance.detik.com/industri/d-6521033/s...,menteri investasi kepala badan koordinasi tana...
4,4,2023-01-17,ekonomi,"Banyak Hotel Dijual Usai Pandemi, Pengusaha Un...",https://finance.detik.com/properti/d-6520841/b...,hotel jual situs jual beli online ketua bpd ...
6,6,2023-01-17,ekonomi,Kepala BIN Beberkan Sederet Faktor Pemicu 2023...,https://finance.detik.com/berita-ekonomi-bisni...,kepala badan intelijen negara bin budi gunaw...
7,7,2023-01-17,ekonomi,Sandiaga Uno Usul Hari Kejepit Jadi Libur Bers...,https://finance.detik.com/berita-ekonomi-bisni...,menteri pariwisata ekonomi kreatif menparekr...
8,8,2023-01-17,ekonomi,Terkuak! 2 Alasan Produsen Sepatu Merek Dunia ...,https://finance.detik.com/berita-ekonomi-bisni...,produsen sepatu merek dunia serang banten pt...
9,9,2023-01-17,ekonomi,"Proyek Tol Terpanjang di RI Dilelang Ulang, Pe...",https://finance.detik.com/infrastruktur/d-6520...,bangun tol gedebage-tasikmalaya-cilacap getac...
13,13,2023-01-17,ekonomi,RI Butuh Investasi Rp 8.280 T buat Genjot Hili...,https://finance.detik.com/berita-ekonomi-bisni...,menteri investasi kepala badan koordinasi tana...
14,14,2023-01-17,ekonomi,"Soal Bentrok di PT GNI, Bahlil: Jangan Digemba...",https://finance.detik.com/industri/d-6521033/s...,menteri investasi kepala badan koordinasi tana...
16,16,2023-01-17,ekonomi,"Banyak Hotel Dijual Usai Pandemi, Pengusaha Un...",https://finance.detik.com/properti/d-6520841/b...,hotel jual situs jual beli online ketua bpd ...
18,18,2023-01-17,ekonomi,Kepala BIN Beberkan Sederet Faktor Pemicu 2023...,https://finance.detik.com/berita-ekonomi-bisni...,kepala badan intelijen negara bin budi gunaw...
19,19,2023-01-17,ekonomi,Sandiaga Uno Usul Hari Kejepit Jadi Libur Bers...,https://finance.detik.com/berita-ekonomi-bisni...,menteri pariwisata ekonomi kreatif menparekr...
20,20,2023-01-17,ekonomi,Terkuak! 2 Alasan Produsen Sepatu Merek Dunia ...,https://finance.detik.com/berita-ekonomi-bisni...,produsen sepatu merek dunia serang banten pt...
21,21,2023-01-17,ekonomi,"Proyek Tol Terpanjang di RI Dilelang Ulang, Pe...",https://finance.detik.com/infrastruktur/d-6520...,bangun tol gedebage-tasikmalaya-cilacap getac...

In [ ]:
berita_saham=berita_saham.drop(columns=['Unnamed: 0'])
berita_saham

,tanggal,kategori,judul,url,konten_clean
1,2023-01-17,ekonomi,RI Butuh Investasi Rp 8.280 T buat Genjot Hili...,https://finance.detik.com/berita-ekonomi-bisni...,menteri investasi kepala badan koordinasi tana...
2,2023-01-17,ekonomi,"Soal Bentrok di PT GNI, Bahlil: Jangan Digemba...",https://finance.detik.com/industri/d-6521033/s...,menteri investasi kepala badan koordinasi tana...
4,2023-01-17,ekonomi,"Banyak Hotel Dijual Usai Pandemi, Pengusaha Un...",https://finance.detik.com/properti/d-6520841/b...,hotel jual situs jual beli online ketua bpd ...
6,2023-01-17,ekonomi,Kepala BIN Beberkan Sederet Faktor Pemicu 2023...,https://finance.detik.com/berita-ekonomi-bisni...,kepala badan intelijen negara bin budi gunaw...
7,2023-01-17,ekonomi,Sandiaga Uno Usul Hari Kejepit Jadi Libur Bers...,https://finance.detik.com/berita-ekonomi-bisni...,menteri pariwisata ekonomi kreatif menparekr...
8,2023-01-17,ekonomi,Terkuak! 2 Alasan Produsen Sepatu Merek Dunia ...,https://finance.detik.com/berita-ekonomi-bisni...,produsen sepatu merek dunia serang banten pt...
9,2023-01-17,ekonomi,"Proyek Tol Terpanjang di RI Dilelang Ulang, Pe...",https://finance.detik.com/infrastruktur/d-6520...,bangun tol gedebage-tasikmalaya-cilacap getac...
13,2023-01-17,ekonomi,RI Butuh Investasi Rp 8.280 T buat Genjot Hili...,https://finance.detik.com/berita-ekonomi-bisni...,menteri investasi kepala badan koordinasi tana...
14,2023-01-17,ekonomi,"Soal Bentrok di PT GNI, Bahlil: Jangan Digemba...",https://finance.detik.com/industri/d-6521033/s...,menteri investasi kepala badan koordinasi tana...
16,2023-01-17,ekonomi,"Banyak Hotel Dijual Usai Pandemi, Pengusaha Un...",https://finance.detik.com/properti/d-6520841/b...,hotel jual situs jual beli online ketua bpd ...
18,2023-01-17,ekonomi,Kepala BIN Beberkan Sederet Faktor Pemicu 2023...,https://finance.detik.com/berita-ekonomi-bisni...,kepala badan intelijen negara bin budi gunaw...
19,2023-01-17,ekonomi,Sandiaga Uno Usul Hari Kejepit Jadi Libur Bers...,https://finance.detik.com/berita-ekonomi-bisni...,menteri pariwisata ekonomi kreatif menparekr...
20,2023-01-17,ekonomi,Terkuak! 2 Alasan Produsen Sepatu Merek Dunia ...,https://finance.detik.com/berita-ekonomi-bisni...,produsen sepatu merek dunia serang banten pt...
21,2023-01-17,ekonomi,"Proyek Tol Terpanjang di RI Dilelang Ulang, Pe...",https://finance.detik.com/infrastruktur/d-6520...,bangun tol gedebage-tasikmalaya-cilacap getac...

In [ ]:
print("jumlah data awal", len(df))
print("jumlah berita saham", len(berita_saham))

jumlah data awal 24
jumlah berita saham 14

In [ ]:
berita_saham.to_csv("ALL_SAHAM_RELEVANCY_NEWS2.csv")

In [ ]:
df = pd.read_csv("ALL_SAHAM_RELEVANCY_NEWS2.csv")
df

,Unnamed: 0,tanggal,kategori,judul,url,konten_clean
0,1,2023-01-17,ekonomi,RI Butuh Investasi Rp 8.280 T buat Genjot Hili...,https://finance.detik.com/berita-ekonomi-bisni...,menteri investasi kepala badan koordinasi tana...
1,2,2023-01-17,ekonomi,"Soal Bentrok di PT GNI, Bahlil: Jangan Digemba...",https://finance.detik.com/industri/d-6521033/s...,menteri investasi kepala badan koordinasi tana...
2,4,2023-01-17,ekonomi,"Banyak Hotel Dijual Usai Pandemi, Pengusaha Un...",https://finance.detik.com/properti/d-6520841/b...,hotel jual situs jual beli online ketua bpd ...
3,6,2023-01-17,ekonomi,Kepala BIN Beberkan Sederet Faktor Pemicu 2023...,https://finance.detik.com/berita-ekonomi-bisni...,kepala badan intelijen negara bin budi gunaw...
4,7,2023-01-17,ekonomi,Sandiaga Uno Usul Hari Kejepit Jadi Libur Bers...,https://finance.detik.com/berita-ekonomi-bisni...,menteri pariwisata ekonomi kreatif menparekr...
5,8,2023-01-17,ekonomi,Terkuak! 2 Alasan Produsen Sepatu Merek Dunia ...,https://finance.detik.com/berita-ekonomi-bisni...,produsen sepatu merek dunia serang banten pt...
6,9,2023-01-17,ekonomi,"Proyek Tol Terpanjang di RI Dilelang Ulang, Pe...",https://finance.detik.com/infrastruktur/d-6520...,bangun tol gedebage-tasikmalaya-cilacap getac...
7,13,2023-01-17,ekonomi,RI Butuh Investasi Rp 8.280 T buat Genjot Hili...,https://finance.detik.com/berita-ekonomi-bisni...,menteri investasi kepala badan koordinasi tana...
8,14,2023-01-17,ekonomi,"Soal Bentrok di PT GNI, Bahlil: Jangan Digemba...",https://finance.detik.com/industri/d-6521033/s...,menteri investasi kepala badan koordinasi tana...
9,16,2023-01-17,ekonomi,"Banyak Hotel Dijual Usai Pandemi, Pengusaha Un...",https://finance.detik.com/properti/d-6520841/b...,hotel jual situs jual beli online ketua bpd ...
10,18,2023-01-17,ekonomi,Kepala BIN Beberkan Sederet Faktor Pemicu 2023...,https://finance.detik.com/berita-ekonomi-bisni...,kepala badan intelijen negara bin budi gunaw...
11,19,2023-01-17,ekonomi,Sandiaga Uno Usul Hari Kejepit Jadi Libur Bers...,https://finance.detik.com/berita-ekonomi-bisni...,menteri pariwisata ekonomi kreatif menparekr...
12,20,2023-01-17,ekonomi,Terkuak! 2 Alasan Produsen Sepatu Merek Dunia ...,https://finance.detik.com/berita-ekonomi-bisni...,produsen sepatu merek dunia serang banten pt...
13,21,2023-01-17,ekonomi,"Proyek Tol Terpanjang di RI Dilelang Ulang, Pe...",https://finance.detik.com/infrastruktur/d-6520...,bangun tol gedebage-tasikmalaya-cilacap getac...

In [ ]:
df=df.drop(columns=["Unnamed: 0"])
df.head()

,tanggal,kategori,judul,url,konten_clean
0,2023-01-17,ekonomi,RI Butuh Investasi Rp 8.280 T buat Genjot Hili...,https://finance.detik.com/berita-ekonomi-bisni...,menteri investasi kepala badan koordinasi tana...
1,2023-01-17,ekonomi,"Soal Bentrok di PT GNI, Bahlil: Jangan Digemba...",https://finance.detik.com/industri/d-6521033/s...,menteri investasi kepala badan koordinasi tana...
2,2023-01-17,ekonomi,"Banyak Hotel Dijual Usai Pandemi, Pengusaha Un...",https://finance.detik.com/properti/d-6520841/b...,hotel jual situs jual beli online ketua bpd ...
3,2023-01-17,ekonomi,Kepala BIN Beberkan Sederet Faktor Pemicu 2023...,https://finance.detik.com/berita-ekonomi-bisni...,kepala badan intelijen negara bin budi gunaw...
4,2023-01-17,ekonomi,Sandiaga Uno Usul Hari Kejepit Jadi Libur Bers...,https://finance.detik.com/berita-ekonomi-bisni...,menteri pariwisata ekonomi kreatif menparekr...

In [ ]:
df.isna().sum()

tanggal         0
kategori        0
judul           0
url             0
konten_clean    0
dtype: int64

In [ ]:
!pip install -q transformers torch pandas

import pandas as pd
import re
import torch
from transformers import pipeline, AutoTokenizer, AutoModelForSequenceClassification

# ========== 1. Load model & tokenizer yang benar ==========
MODEL_ID = "taufiqdp/indonesian-sentiment"  # ini model yang tersedia publik :contentReference[oaicite:1]{index=1}

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
model = AutoModelForSequenceClassification.from_pretrained(MODEL_ID)

print("Label mapping (id2label):", model.config.id2label)

device = 0 if torch.cuda.is_available() else -1
sentiment_pipe = pipeline(
    "text-classification",
    model=model,
    tokenizer=tokenizer,
    device=device,
    return_all_scores=False
)

Device set to use cpu

Label mapping (id2label): {0: 'negatif', 1: 'netral', 2: 'positif'}

/usr/local/lib/python3.12/dist-packages/transformers/pipelines/text_classification.py:111: UserWarning: `return_all_scores` is now deprecated,  if want a similar functionality use `top_k=None` instead of `return_all_scores=True` or `top_k=1` instead of `return_all_scores=False`.
  warnings.warn(

In [ ]:
# ========== 2. Fungsi batch prediksi ==========
def predict_batch(texts, batch_size=32):
    results = []
    for i in range(0, len(texts), batch_size):
        batch = texts[i : i + batch_size]
        preds = sentiment_pipe(batch, truncation=True, max_length=512)
        results.extend(preds)
    return results

In [ ]:
# ========== 3. Keyword saham vs override ==========
positif_keywords = [
    "menguat", "rebound", "bullish", "surplus", "naik", "melonjak",
    "penguatan", "stabil", "optimis", "pulih", "rekor", "melambung"
]
negatif_keywords = [
    "melemah", "anjlok", "bearish", "defisit", "turun", "merosot",
    "penurunan", "tertekan", "resesi", "krisis", "minus", "collapse", "pelemahan"
]

positif_pattern = re.compile(r"\b(" + "|".join(positif_keywords) + r")\b", re.IGNORECASE)
negatif_pattern = re.compile(r"\b(" + "|".join(negatif_keywords) + r")\b", re.IGNORECASE)

def apply_keyword_override(text, model_label, model_score):
    pos_match = bool(positif_pattern.search(text))
    neg_match = bool(negatif_pattern.search(text))

    if pos_match and not neg_match:
        return "positif", 1.0
    elif neg_match and not pos_match:
        return "negatif", 1.0
    elif pos_match and neg_match:
        # kalau kedua jenis keyword ada, pilih berdasarkan jumlah kemunculan
        pos_count = len(positif_pattern.findall(text))
        neg_count = len(negatif_pattern.findall(text))
        if pos_count > neg_count:
            return "positif", 1.0
        elif neg_count > pos_count:
            return "negatif", 1.0
        else:
            # seimbang → fallback ke hasil model
            return model_label, model_score
    else:
        # tidak ada keyword → pake hasil model
        return model_label, model_score

In [ ]:
# ========== 4. Proses DataFrame ==========
# Pastikan kamu punya DataFrame `df` dan ada kolom teks, misalnya “konten_clean”
df["konten_clean"] = df["konten_clean"].fillna("").astype(str)

preds = predict_batch(df["konten_clean"].tolist(), batch_size=32)
df["sentiment_label_model"] = [p["label"] for p in preds]
df["sentiment_score_model"] = [float(p["score"]) for p in preds]

# Model memberikan label default seperti "NEGATIVE", "NEUTRAL", "POSITIVE" atau tergantung id2label
# Kita bisa peta label ke bahasa Indonesia kalau ingin:
# Misal id2label = {0: "negative", 1: "neutral", 2: "positive"}
# Pastikan model.config.id2label terlebih dahulu

# Jika id2label mapping dalam bahasa Inggris, ubah ke bahasa Indonesia:
mapping = {}
for idx, lbl in model.config.id2label.items():
    lbl_low = lbl.lower()
    if "neg" in lbl_low:
        mapping[lbl] = "negatif"
    elif "neu" in lbl_low:
        mapping[lbl] = "netral"
    elif "pos" in lbl_low:
        mapping[lbl] = "positif"
    else:
        mapping[lbl] = lbl  # fallback

# Ubah label model ke versi Indonesia
df["sentiment_label_model_id"] = df["sentiment_label_model"].map(mapping).fillna(df["sentiment_label_model"])

# override keyword
adjusted = [
    apply_keyword_override(text, lbl_id, scr)
    for text, lbl_id, scr in zip(df["konten_clean"],
                                 df["sentiment_label_model_id"],
                                 df["sentiment_score_model"])
]
df["sentiment_label"], df["sentiment_score"] = zip(*adjusted)

In [ ]:
# ========== 5. Simpan + cek distribusi ==========
df.to_csv("df_sentiment_saham_taufiqdp3.csv", index=False)
print("Selesai — file ditulis: df_sentiment_saham_taufiqdp.csv")
print("Distribusi sentiment_label:", df["sentiment_label"].value_counts())

Selesai — file ditulis: df_sentiment_saham_taufiqdp.csv
Distribusi sentiment_label: sentiment_label
netral     8
negatif    6
Name: count, dtype: int64

In [ ]:
df=pd.read_csv("df_sentiment_saham_taufiqdp3.csv")
df

,tanggal,kategori,judul,url,konten_clean,sentiment_label_model,sentiment_score_model,sentiment_label_model_id,sentiment_label,sentiment_score
0,2023-01-17,ekonomi,RI Butuh Investasi Rp 8.280 T buat Genjot Hili...,https://finance.detik.com/berita-ekonomi-bisni...,menteri investasi kepala badan koordinasi tana...,netral,0.507090,netral,netral,0.507090
1,2023-01-17,ekonomi,"Soal Bentrok di PT GNI, Bahlil: Jangan Digemba...",https://finance.detik.com/industri/d-6521033/s...,menteri investasi kepala badan koordinasi tana...,negatif,0.914238,negatif,negatif,0.914238
2,2023-01-17,ekonomi,"Banyak Hotel Dijual Usai Pandemi, Pengusaha Un...",https://finance.detik.com/properti/d-6520841/b...,hotel jual situs jual beli online ketua bpd ...,netral,0.924078,netral,netral,0.924078
3,2023-01-17,ekonomi,Kepala BIN Beberkan Sederet Faktor Pemicu 2023...,https://finance.detik.com/berita-ekonomi-bisni...,kepala badan intelijen negara bin budi gunaw...,negatif,0.882700,negatif,negatif,1.000000
4,2023-01-17,ekonomi,Sandiaga Uno Usul Hari Kejepit Jadi Libur Bers...,https://finance.detik.com/berita-ekonomi-bisni...,menteri pariwisata ekonomi kreatif menparekr...,netral,0.957639,netral,netral,0.957639
5,2023-01-17,ekonomi,Terkuak! 2 Alasan Produsen Sepatu Merek Dunia ...,https://finance.detik.com/berita-ekonomi-bisni...,produsen sepatu merek dunia serang banten pt...,netral,0.947476,netral,negatif,1.000000
6,2023-01-17,ekonomi,"Proyek Tol Terpanjang di RI Dilelang Ulang, Pe...",https://finance.detik.com/infrastruktur/d-6520...,bangun tol gedebage-tasikmalaya-cilacap getac...,netral,0.982098,netral,netral,0.982098
7,2023-01-17,ekonomi,RI Butuh Investasi Rp 8.280 T buat Genjot Hili...,https://finance.detik.com/berita-ekonomi-bisni...,menteri investasi kepala badan koordinasi tana...,netral,0.507090,netral,netral,0.507090
8,2023-01-17,ekonomi,"Soal Bentrok di PT GNI, Bahlil: Jangan Digemba...",https://finance.detik.com/industri/d-6521033/s...,menteri investasi kepala badan koordinasi tana...,negatif,0.914238,negatif,negatif,0.914238
9,2023-01-17,ekonomi,"Banyak Hotel Dijual Usai Pandemi, Pengusaha Un...",https://finance.detik.com/properti/d-6520841/b...,hotel jual situs jual beli online ketua bpd ...,netral,0.924078,netral,netral,0.924078
10,2023-01-17,ekonomi,Kepala BIN Beberkan Sederet Faktor Pemicu 2023...,https://finance.detik.com/berita-ekonomi-bisni...,kepala badan intelijen negara bin budi gunaw...,negatif,0.882700,negatif,negatif,1.000000
11,2023-01-17,ekonomi,Sandiaga Uno Usul Hari Kejepit Jadi Libur Bers...,https://finance.detik.com/berita-ekonomi-bisni...,menteri pariwisata ekonomi kreatif menparekr...,netral,0.957639,netral,netral,0.957639
12,2023-01-17,ekonomi,Terkuak! 2 Alasan Produsen Sepatu Merek Dunia ...,https://finance.detik.com/berita-ekonomi-bisni...,produsen sepatu merek dunia serang banten pt...,netral,0.947476,netral,negatif,1.000000
13,2023-01-17,ekonomi,"Proyek Tol Terpanjang di RI Dilelang Ulang, Pe...",https://finance.detik.com/infrastruktur/d-6520...,bangun tol gedebage-tasikmalaya-cilacap getac...,netral,0.982098,netral,netral,0.982098

In [ ]:
# Pilih hanya kolom yang penting
df = df[[
    "tanggal", "kategori", "judul", "url",
    "konten_clean", "sentiment_label", "sentiment_score"
]]

In [ ]:
df.sentiment_label.value_counts()

sentiment_label
netral     8
negatif    6
Name: count, dtype: int64

In [ ]:
from sklearn.utils import resample

# Pisahkan per kelas
df_net = df[df["sentiment_label"] == "netral"]
df_neg = df[df["sentiment_label"] == "negatif"]

# Target jumlah
TARGET = 7

# Resampling
df_net_bal = resample(df_net, replace=False, n_samples=TARGET, random_state=42)  # undersample
df_neg_bal = resample(df_neg, replace=True,  n_samples=TARGET, random_state=42)  # oversample

# Gabung lagi
df = pd.concat([df_net_bal, df_neg_bal])

# Shuffle biar acak
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

# Simpan
print("Selesai — data balanced disimpan ke df_sentiment_saham_balanced.csv")
print("Distribusi baru:")
print(df["sentiment_label"].value_counts())

Selesai — data balanced disimpan ke df_sentiment_saham_balanced.csv
Distribusi baru:
sentiment_label
negatif    7
netral     7
Name: count, dtype: int64

In [ ]:
df.to_csv("df_sentiment_saham_balanced2.csv", index=False)

In [ ]:
import pandas as pd

# Load data saham yang sudah dibersihkan
df_saham = pd.read_csv("DATA_SAHAM_22-24_CLEAN.csv")
df_saham["tanggal"] = pd.to_datetime(df_saham["tanggal"], errors="coerce")

# Load data sentimen yang sudah dibalance
df_sentimen = pd.read_csv("df_sentiment_saham_balanced2.csv")
df_sentimen["tanggal"] = pd.to_datetime(df_sentimen["tanggal"], errors="coerce")

# --- Agregasi sentimen per tanggal ---
agg_sentimen = df_sentimen.groupby("tanggal").agg(
    avg_sentiment=("sentiment_score", "mean"),
    prop_pos=("sentiment_label", lambda x: (x=="positif").mean()),
    prop_neg=("sentiment_label", lambda x: (x=="negatif").mean()),
    max_impact=("sentiment_label", lambda x: x.value_counts().idxmax())
).reset_index()

# --- Merge ke data saham ---
df_final = pd.merge(df_saham, agg_sentimen, on="tanggal", how="left")

print("Data akhir:", df_final.shape)
df_final

Data akhir: (725, 11)

,tanggal,Terakhir,Pembukaan,Tertinggi,Terendah,Vol.,Perubahan%,avg_sentiment,prop_pos,prop_neg,max_impact
0,2022-01-03,666531.0,658626.0,667720.0,658613.0,1.826000e+10,1.27,NaN,NaN,NaN,NaN
1,2022-01-04,669537.0,667513.0,672066.0,667513.0,1.859000e+10,0.45,NaN,NaN,NaN,NaN
2,2022-01-05,666230.0,670317.0,673811.0,663484.0,1.791000e+10,-0.49,NaN,NaN,NaN,NaN
3,2022-01-06,665335.0,667485.0,667985.0,659323.0,1.800000e+10,-0.13,NaN,NaN,NaN,NaN
4,2022-01-07,670132.0,666951.0,671215.0,664771.0,1.571000e+10,0.72,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
720,2024-12-20,698387.0,698017.0,703240.0,693158.0,1.457000e+10,0.09,NaN,NaN,NaN,NaN
721,2024-12-23,709644.0,703753.0,709644.0,703573.0,1.387000e+10,1.61,NaN,NaN,NaN,NaN
722,2024-12-24,706575.0,711564.0,712058.0,706375.0,1.106000e+10,-0.43,NaN,NaN,NaN,NaN
723,2024-12-27,703657.0,707338.0,710027.0,702471.0,1.443000e+10,-0.41,NaN,NaN,NaN,NaN
724,2024-12-30,707990.0,702678.0,707990.0,699307.0,1.597000e+10,0.62,NaN,NaN,NaN,NaN

In [ ]:
df_final = df_final[df_final["tanggal"] == "2023-01-17"]
df_final
# df_final.to_csv("ihsg_sentimen_features3.csv", index=False)

,tanggal,Terakhir,Pembukaan,Tertinggi,Terendah,Vol.,Perubahan%,avg_sentiment,prop_pos,prop_neg,max_impact
258,2023-01-17,676734.0,668806.0,680187.0,668806.0,2.176000e+10,1.19,0.900903,0.0,0.5,negatif

In [ ]:
def categorize_sentiment(score, pos_thresh=0.6, neg_thresh=0.4):
    if pd.isna(score):
        return "tidak ada data"
    elif score >= pos_thresh:
        return "positif"
    elif score <= neg_thresh:
        return "negatif"
    else:
        return "netral"

In [ ]:
df_final["avg_sentiment_result"] = df_final["avg_sentiment"].apply(categorize_sentiment)

/tmp/ipython-input-847757208.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final["avg_sentiment_result"] = df_final["avg_sentiment"].apply(categorize_sentiment)

In [ ]:
df_final

,tanggal,Terakhir,Pembukaan,Tertinggi,Terendah,Vol.,Perubahan%,avg_sentiment,prop_pos,prop_neg,max_impact,avg_sentiment_result
258,2023-01-17,676734.0,668806.0,680187.0,668806.0,2.176000e+10,1.19,0.900903,0.0,0.5,negatif,positif

In [ ]:
df_final = df_final[df_final["tanggal"] == "2023-01-17"]
df_final.to_csv("ihsg_sentimen_features3.csv", index=False)